### ISSUE TITLE
Ctrl + c in terminal doesn't close application

### ISSUE THREAD

**Issue by jokuNimi** [bil-elmoussaoui/Icon-Requests#14]
Pressing ctrl and c in terminal doesn't close the application. The application doesn't report anything:
```
$ icon-requests --debug
[DEBUG] - 2017-03-18 23:48:20 - Loading css file 
[DEBUG] - 2017-03-18 23:48:20 - Starting new HTTPS connection (1): api.github.com
^C^C^C
```
and there isn't anything in system logs either. kill [icon-requests PID] works though:
```
^C^C^Cfish: 'icon-requests --debug' terminated by signal SIGTERM (Polite quit request)
```
The sequence does have some effect though. If I click on most things (anything but the tab headings) in the app after typing ctrl + c, it seems to cancel that click. Some output:
```
^C^CTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/IconRequests/widgets/application_row.py", line 150, in report_missing_icon
    def report_missing_icon(self, *args):
KeyboardInterrupt
```
```
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/IconRequests/widgets/window.py", line 101, in __on_key_press
    def __on_key_press(self, widget, event):
KeyboardInterrupt
```
```
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/IconRequests/widgets/window.py", line 153, in show_menu_popover
    def show_menu_popover(self, *args):
KeyboardInterrupt
```

**Comment by bilelmoussaoui** [comment]
Fixed on beta branch.
