### ISSUE TITLE
Can't build on Ubuntu

### ISSUE THREAD

**Issue by theel0ja** [bil-elmoussaoui/Icon-Requests#18]
```
theel0ja@mursu-1 ~/icon-requests/icon-requests-0.1.2/build $ sudo apt install gobject-introspection 
Luetaan pakettiluetteloita... Valmis
Muodostetaan riippuvuussuhteiden puu       
Luetaan tilatiedot... Valmis        
gobject-introspection is already the newest version (1.46.0-3ubuntu1).
0 päivitetty, 0 uutta asennusta, 0 poistettavaa ja 1 päivittämätöntä.
theel0ja@mursu-1 ~/icon-requests/icon-requests-0.1.2/build $ meson ..
The Meson build system
Version: 0.29.0
Source dir: /home/theel0ja/icon-requests/icon-requests-0.1.2
Build dir: /home/theel0ja/icon-requests/icon-requests-0.1.2/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: icon-requests
Native c compiler: cc (gcc 5.4.0-6ubuntu1)
Message: Looking for dependencies
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Program intltool-merge found: YES (/usr/bin/intltool-merge)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.48.2
Native dependency gobject-2.0 found: YES 2.48.2

Meson encountered an error in file meson.build, line 15, column 0:
Native dependency gobject-introspection-1.0 not found.
theel0ja@mursu-1 ~/icon-requests-0.1.2/build $ 
```

**Comment by theel0ja** [comment]
Fixed, needed package `libgirepository1.0-dev`

**Comment by bilelmoussaoui** [comment]
Is everything working as expected right now? :)

**Comment by theel0ja** [comment]
No, problem with mesonbuild.modules.i18n...

```
theel0ja@mursu-1 ~/icon-requests/icon-requests-0.1.2/build $ meson ..
The Meson build system
Version: 0.29.0
Source dir: /home/theel0ja/Asiakirjat/DebBuild/icon-requests/icon-requests-0.1.2
Build dir: /home/theel0ja/Asiakirjat/DebBuild/icon-requests/icon-requests-0.1.2/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: icon-requests
Native c compiler: cc (gcc 5.4.0-6ubuntu1)
Message: Looking for dependencies
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Program intltool-merge found: YES (/usr/bin/intltool-merge)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.48.2
Native dependency gobject-2.0 found: YES 2.48.2
Native dependency gobject-introspection-1.0 found: YES 1.46.0
Native dependency gtk+-3.0 found: YES 3.18.9
Message: Getting python install dir
Message: Python install dir found : YES /usr/lib/python3/dist-packages
Message: post install script is : enabled
Warning, glib compiled dependencies will not work until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
Message: TODO: Compiling resources
Warning: Unknown keyword arguments in target icon-requests_c: gresource_bundle
Warning: Unknown keyword arguments in target icon-requests_h: gresource_bundle
Message: Compiling schemas
Message: TODO: Making a .desktop file
Message: TODO: Preparing appdata
Message: TODO: Making a list of icons
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 250, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 160, in generate
    intr.run()
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1028, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1050, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1044, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1160, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1957, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 62, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1773, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1050, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1044, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1162, in evaluate_statement
    return self.assignment(cur)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1976, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1160, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1957, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 70, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 62, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1097, in func_import
    module = importlib.import_module('mesonbuild.modules.' + modname).initialize()
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'mesonbuild.modules.i18n'
theel0ja@mursu-1 ~/icon-requests/icon-requests-0.1.2/build $ 
```

**Comment by bilelmoussaoui** [comment]
Do you have gettext?

**Comment by theel0ja** [comment]
Yes.

```
theel0ja@mursu-1 ~ $ sudo apt install gettext
Luetaan pakettiluetteloita... Valmis
Muodostetaan riippuvuussuhteiden puu       
Luetaan tilatiedot... Valmis        
gettext is already the newest version (0.19.7-2ubuntu3).
0 päivitetty, 0 uutta asennusta, 0 poistettavaa ja 1 päivittämätöntä.
theel0ja@mursu-1 ~ $ 
```

**Comment by bilelmoussaoui** [comment]
You must have something missing with your meson installation :( https://github.com/mesonbuild/meson/wiki/i18n-module
Try using `sudo pip3 install meson` or `sudo pip3 install meson --upgrade`

**Comment by theel0ja** [comment]
It works! :)

**Comment by bilelmoussaoui** [comment]
Perfect! :)
