### ISSUE TITLE
Desktop files not Loading when when there is an invalid desktop file

### ISSUE THREAD

**Issue by arshubham** [bil-elmoussaoui/Icon-Requests#23]
Debug Info: 
```
[DEBUG] - 2017-12-12 22:58:31 - Loading css file 
[INFO] - 2017-12-12 22:58:32 - Starting new HTTPS connection (1): api.github.com
[DEBUG] - 2017-12-12 22:58:34 - "GET /repos/PapirusDevelopmentTeam/papirus-icon-theme/issues?page=1&per_page=100&state=open HTTP/1.1" 200 None
[INFO] - 2017-12-12 22:58:34 - Starting new HTTPS connection (1): api.github.com
[DEBUG] - 2017-12-12 22:58:36 - "GET /repos/PapirusDevelopmentTeam/papirus-icon-theme/issues?page=2&per_page=100&state=open HTTP/1.1" 200 2
[INFO] - 2017-12-12 22:58:36 - Starting new HTTPS connection (1): api.github.com
[DEBUG] - 2017-12-12 22:58:39 - "GET /repos/PapirusDevelopmentTeam/papirus-icon-theme/issues?page=3&per_page=100&state=open HTTP/1.1" 200 2
[INFO] - 2017-12-12 22:58:39 - Starting new HTTPS connection (1): api.github.com
[DEBUG] - 2017-12-12 22:58:41 - "GET /repos/PapirusDevelopmentTeam/papirus-icon-theme/issues?page=4&per_page=100&state=open HTTP/1.1" 200 2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/IconRequests/widgets/window.py", line 184, in generate_apps_list
    supported_icons, issues_list)
  File "/usr/lib/python3/dist-packages/IconRequests/modules/desktop.py", line 15, in __init__
    DesktopEntry.__init__(self, filename=_file)
  File "/usr/lib/python3/dist-packages/xdg/DesktopEntry.py", line 33, in __init__
    self.parse(filename)
  File "/usr/lib/python3/dist-packages/xdg/DesktopEntry.py", line 42, in parse
    IniFile.parse(self, file, ["Desktop Entry", "KDE Desktop Entry"])
  File "/usr/lib/python3/dist-packages/xdg/IniFile.py", line 104, in parse
    raise ParsingError("[%s]-Header missing" % headers[0], filename)
xdg.Exceptions.ParsingError: ParsingError in file '/home/shubhamarora/.local/share/applications/appeditor-local-application-5.desktop', [Desktop Entry]-Header missing
```
appeditor-local-application-5.desktop is an empty File

Ideally it should skip invalid files and show some message.

**Comment by bilelmoussaoui** [comment]
Will fix that on the beta branch, the fix should be released on the next version (not sure when it's going to happen)

**Comment by bilelmoussaoui** [comment]
Fixed on beta.
